{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hackathon-app.secretName" . }}
  labels:
    {{- include "hackathon-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  BETTER_AUTH_SECRET: {{ .Values.secrets.betterAuthSecret | quote }}
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | quote }}
{{- end }}
